import './style.css';
import './enhancements.css';
import './resale.css';
import './auth.css';
import './ticket-security.css';
import './marketplace.css';
import './marketplace.js';

const events = [
  { id: 1, name: 'Neon Nights: Live in Mumbai', type: 'Music', date: 'AUG 24', time: '7:30 PM', duration: '3 hours', venue: 'Dome, NSCI', location: 'Lala Lajpatrai Marg, Worli, Mumbai 400018', city: 'Mumbai', price: 1499, stock: 72, total: 500, image: 'neon', description: 'An electric night of synth-pop, neon visuals, and the artists shaping India’s new sound.', organizer: 'Sonic Collective' },
  { id: 2, name: 'India vs Australia · T20', type: 'Sports', date: 'SEP 03', time: '7:00 PM', duration: '3.5 hours', venue: 'Wankhede Stadium', location: 'D Road, Churchgate, Mumbai 400020', city: 'Mumbai', price: 2000, stock: 145, total: 1000, image: 'cricket', description: 'Experience international cricket from the stands with an authentic, transferable on-chain ticket.', organizer: 'Stadium Live' },
  { id: 3, name: 'Future of AI Summit 2026', type: 'Technology', date: 'SEP 18', time: '9:00 AM', duration: '8 hours', venue: 'Jio World Centre', location: 'G Block, Bandra Kurla Complex, Mumbai 400051', city: 'Mumbai', price: 999, stock: 48, total: 200, image: 'ai', description: 'A day with builders, researchers, and founders advancing India’s AI ecosystem.', organizer: 'Tech Forward' },
  { id: 4, name: 'Laugh Track: Stand-up Special', type: 'Comedy', date: 'OCT 02', time: '8:00 PM', duration: '2 hours', venue: 'The Royal Opera House', location: 'Mama Parmanand Marg, Charni Road, Mumbai 400004', city: 'Mumbai', price: 799, stock: 26, total: 300, image: 'comedy', description: 'Fresh comedy, no screenshots, no fake tickets—just a great seat and a great night.', organizer: 'Mic Drop' },
  { id: 5, name: 'Mumbai Design Week', type: 'Workshop', date: 'OCT 12', time: '10:00 AM', duration: '6 hours', venue: 'Nehru Centre', location: 'Dr Annie Besant Road, Worli, Mumbai 400018', city: 'Mumbai', price: 599, stock: 84, total: 250, image: 'design', description: 'Hands-on sessions for designers, students, and creative teams.', organizer: 'Design Mumbai' },
  { id: 6, name: 'Indie Film Under the Stars', type: 'Arts', date: 'OCT 26', time: '6:30 PM', duration: '4 hours', venue: 'Mehboob Studios', location: '100 Hill Road, Bandra West, Mumbai 400050', city: 'Mumbai', price: 899, stock: 112, total: 400, image: 'film', description: 'An open-air screening, filmmaker conversations, and a community night.', organizer: 'Frame by Frame' }
];

let state = { view: 'home', selected: 0, wallet: false, authenticated: false, role: 'customer', booked: false, tab: 'overview', filter: 'All events', search: '', balance: 4000, resaleListing: null, resaleSold: false, loginCode: '', entryCode: '', ticketTokenId: null, ticketRedeemed: false, user: { name: 'Riya Sharma', email: 'riya.sharma@example.com', phone: '+91 98765 43210', city: 'Mumbai' } };
const inr = n => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);

function header() {
  return `<header><button class="brand" onclick="go('home')"><span class="brand-mark">B</span>BlockTix</button><nav><button onclick="go('home')">Explore events</button><button onclick="go('tickets')">My tickets</button><button class="organizer-link" onclick="go('dashboard')">For organizers <span>↗</span></button></nav><div class="account-actions">${state.authenticated ? `<button class="user-pill" onclick="openAccount()"><span>${state.user.name.split(' ').map(n => n[0]).join('')}</span>${state.user.name.split(' ')[0]}</button>` : `<button class="sign-in" onclick="openAuth()">Sign in</button>`}<button class="wallet ${state.wallet ? 'connected' : ''}" onclick="connectWallet()">${state.wallet ? `● 0x72…A91C <b>${inr(state.balance)}</b>` : 'Connect wallet'}</button></div><button class="mobile-menu">☰</button></header>`;
}

function polygonBadge() { return `<span class="polygon-badge"><i></i> Polygon Amoy</span>`; }
function eventArt(type, large = false) { const labels = { neon: 'NIGHT\nSHIFT', cricket: 'INDIA\nV AUS', ai: 'THE\nFUTURE', comedy: 'LAUGH\nLOUD', design: 'MAKE\nMORE', film: 'OPEN\nAIR' }; return `<div class="event-art ${type} ${large ? 'large' : ''}"><div class="art-grid"></div><div class="orb orb-one"></div><div class="orb orb-two"></div><span class="art-label">${labels[type] || 'EVENT\nPASS'}</span></div>`; }

function home() {
  const filteredEvents = events.filter(e => (state.filter === 'All events' || e.type === state.filter) && `${e.name} ${e.type} ${e.venue} ${e.city}`.toLowerCase().includes(state.search.toLowerCase()));
  return `<main>
    <section class="hero"><div class="hero-copy"><div class="eyebrow">Built for the way events move</div><h1>Tickets you can<br><em>actually own.</em></h1><p>Discover unforgettable events. Every BlockTix ticket is a verifiable NFT on Polygon—secure, transferable, and entirely yours.</p><div class="hero-actions"><button class="primary" onclick="document.getElementById('events').scrollIntoView({behavior:'smooth'})">Explore events <span>→</span></button><button class="text-button" onclick="go('how')">How it works <span>↗</span></button></div><div class="chain-note">${polygonBadge()}<span>Low fees · Fast transactions · Secure ownership</span></div></div><div class="hero-visual"><div class="hero-glow"></div><div class="ticket-float"><div class="ticket-top"><span>BLOCKTIX</span><span>ADMIT ONE</span></div><div class="ticket-main"><span class="tiny">LIVE CONCERT</span><strong>NEON<br>NIGHTS</strong><span>24 AUG · MUMBAI</span></div><div class="ticket-bottom"><span>NFT #0241</span><span class="qr">▦</span></div></div><div class="verified-float"><span>✓</span><div><b>Ownership verified</b><small>Polygon blockchain</small></div></div><div class="stat-float"><b>100%</b><span>authentic</span></div></div></section>
    <section class="trust-row"><div><b>0</b><span>Counterfeit tickets</span></div><div><b>2.4k+</b><span>Tickets minted</span></div><div><b>98%</b><span>Entry in under 2 sec</span></div><div><b>₹0</b><span>Hidden resale fees</span></div></section>
    <section class="events-section" id="events"><div class="section-heading"><div><span class="eyebrow">Happening soon</span><h2>Find your next moment.</h2></div><button class="text-button" onclick="setFilter('All events')">View all events <span>→</span></button></div><div class="event-tools"><label class="search"><span>⌕</span><input type="search" value="${state.search}" oninput="searchEvents(this.value)" placeholder="Search events, venues, or categories" /></label><div class="filters">${['All events', 'Music', 'Sports', 'Technology', 'Comedy'].map(category => `<button class="filter ${state.filter === category ? 'active' : ''}" onclick="setFilter('${category}')">${category}</button>`).join('')}</div></div><p class="results-count">${filteredEvents.length} ${filteredEvents.length === 1 ? 'event' : 'events'} available${state.search || state.filter !== 'All events' ? ` for <b>${state.search || state.filter}</b>` : ''}</p><div class="event-grid">${filteredEvents.length ? filteredEvents.map(event => eventCard(event, events.indexOf(event))).join('') : `<div class="no-results"><b>No events found</b><span>Try another category or search term.</span><button class="secondary" onclick="clearFilters()">Clear filters</button></div>`}</div></section>
    ${state.resaleListing ? resaleMarket() : ''}<section class="ownership"><div class="ownership-copy"><span class="eyebrow">THE BLOCKTIX DIFFERENCE</span><h2>Not just a pass.<br>A proof of <em>ownership.</em></h2><p>Every ticket is a unique NFT, recorded on Polygon. It cannot be copied, faked, or used twice.</p><button class="primary dark" onclick="go('how')">See how it works <span>→</span></button></div><div class="ownership-steps"><div class="step"><span>01</span><div><b>Minted once</b><p>Your ticket is created as a one-of-one NFT.</p></div><i>✦</i></div><div class="step"><span>02</span><div><b>Owned by you</b><p>Only your connected wallet holds the ticket.</p></div><i>⌘</i></div><div class="step"><span>03</span><div><b>Verified at entry</b><p>Scan and redeem it securely in seconds.</p></div><i>✓</i></div></div></section>
  </main>`;
}

function eventCard(e, i) { return `<article class="event-card" onclick="selectEvent(${i})">${eventArt(e.image)}<div class="event-card-body"><div class="event-meta"><span>${e.type}</span><span>${e.date}</span></div><h3>${e.name}</h3><p>${e.venue}, ${e.city}</p><div class="event-time">◷ ${e.time} · ${e.duration}</div><div class="card-bottom"><b>From ${inr(e.price)}</b><span>${e.stock} left</span></div></div></article>`; }
function resaleMarket() { const listing = state.resaleListing; return `<section class="resale-market"><div><span class="eyebrow">AUTHORIZED RESALE MARKET</span><h2>Available from a verified fan.</h2><p>Every resale follows the organizer’s on-chain price cap and royalty rule.</p></div><div class="market-listing"><div class="listing-ticket"><span>BLOCKTIX</span><b>NEON<br>NIGHTS</b><small>Ticket #0241</small></div><div><span class="status valid">● Verified listing</span><h3>Neon Nights: Live in Mumbai</h3><p>General Admission · 24 Aug · Dome, NSCI</p><b class="listing-price">${inr(listing.price)}</b><small>Maximum allowed: ${inr(1649)}</small></div><button class="primary" onclick="buyResale()">Buy resale ticket <span>→</span></button></div></section>`; }

function detail() { const e = events[state.selected]; return `<main class="detail-page"><button class="back" onclick="go('home')">← Back to events</button><div class="detail-grid"><div><div class="detail-art-wrap">${eventArt(e.image, true)}<span class="category-chip">${e.type}</span></div><div class="detail-info"><span class="eyebrow">${e.organizer.toUpperCase()} PRESENTS</span><h1>${e.name}</h1><p class="lead">${e.description}</p><div class="info-list"><div><span>◷</span><p><b>${e.date}, 2026 · ${e.time}</b><small>Duration: ${e.duration} · Doors open 60 minutes before</small></p></div><div><span>⌖</span><p><b>${e.venue}, ${e.city}</b><small>${e.location}</small></p></div></div></div></div><aside class="purchase-card"><div class="purchase-head"><span>General Admission</span>${polygonBadge()}</div><h2>${inr(e.price)}</h2><p>incl. taxes · NFT ticket</p>${state.wallet ? `<div class="wallet-funds"><span>Your demo wallet</span><b>${inr(state.balance)}</b></div>` : ''}<div class="availability"><span><i></i> ${e.stock} tickets remaining</span><b>${Math.round((e.stock/e.total)*100)}% left</b></div><div class="progress"><i style="width:${100-(e.stock/e.total*100)}%"></i></div><div class="quantity"><span>Quantity</span><div><button>−</button><b>1</b><button>+</button></div></div><button class="primary full" onclick="purchase()">${state.wallet ? `Buy NFT ticket · ${inr(e.price)}` : 'Connect wallet to buy'} <span>→</span></button><p class="secure">⌁ Minted on Polygon · Includes a reward NFT</p><div class="resale-rule"><b>↻ Resale protected</b><span>Maximum resale: ${inr(Math.round(e.price*1.1))}<br>5% goes back to the organizer</span></div></aside></div><section class="onchain"><div><span class="eyebrow">ON-CHAIN TICKET</span><h2>What you’re buying</h2></div><div class="chain-grid"><div><span>Ticket NFT</span><b>ERC-721 · #0241</b></div><div><span>Reward NFT</span><b>POAP · #BXT-0241</b></div><div><span>Network</span><b>Polygon Amoy</b></div><div><span>Resale cap</span><b>110% of face value</b></div></div></section></main>`; }

function tickets() { return `<main class="tickets-page"><span class="eyebrow">YOUR COLLECTION</span><h1>My tickets</h1><p class="page-sub">Your event access and rewards, safely stored in your wallet.</p>${state.booked ? `<section class="owned-ticket"><div class="owned-art">${eventArt(events[0].image)}</div><div class="owned-info"><div class="owned-title"><div><span class="status valid">● Valid ticket</span><h2>Neon Nights: Live in Mumbai</h2><p>24 Aug 2026 · 7:30 PM · Dome, NSCI</p></div>${polygonBadge()}</div><div class="nft-data"><div><span>Token ID</span><b>#0241</b></div><div><span>Owner</span><b>0x72d…A91C</b></div><div><span>Standard</span><b>ERC-721</b></div></div><div class="ticket-actions"><button class="secondary" onclick="redeem()">Show entry QR</button><button class="text-button">List for resale →</button></div></div></section><section class="reward-card"><div class="reward-icon">✦</div><div><span class="eyebrow">BONUS COLLECTIBLE MINTED</span><h2>Neon Nights Attendance Badge</h2><p>Your complimentary reward NFT was sent to your wallet with Ticket #0241. Keep it forever, even after the event.</p></div><div class="reward-token"><span>REWARD NFT</span><b>#BXT-0241</b><small>Polygon Amoy</small></div></section><section class="ticket-note"><span>✦</span><div><b>This ticket and its reward are uniquely yours</b><p>Ownership and status are verified by the BlockTix smart contract on Polygon.</p></div><button>View transaction ↗</button></section>` : `<section class="empty"><span>◇</span><h2>No tickets yet</h2><p>When you buy an event ticket, its NFT and a free reward collectible will appear here.</p><button class="primary" onclick="go('home')">Explore events →</button></section>`}</main>`; }

function dashboard() { return `<main class="dashboard"><aside class="side-nav"><button class="brand" onclick="go('home')"><span class="brand-mark">B</span>BlockTix</button><div class="org-profile"><span class="avatar">SC</span><div><b>Sonic Collective</b><small>Organizer account</small></div></div><div class="side-links"><button class="active">▦ Overview</button><button>◈ My events</button><button>◒ Ticket sales</button><button>⌘ Entry scanner</button><button>◌ Settings</button></div><button class="back-site" onclick="go('home')">← Back to marketplace</button></aside><section class="dash-content"><div class="dash-top"><div><span class="eyebrow">ORGANIZER DASHBOARD</span><h1>Good morning, Sonic.</h1></div><button class="primary" onclick="createEvent()">+ Create event</button></div><div class="metrics"><div><span>Gross sales</span><b>₹7,48,500</b><small class="up">↑ 18.2% <i>vs last event</i></small></div><div><span>Tickets sold</span><b>428 <i>/ 500</i></b><small>85.6% capacity</small></div><div><span>On-chain transfers</span><b>31</b><small>All verified on Polygon</small></div><div><span>Entry redeemed</span><b>0</b><small>Event in 5 days</small></div></div><section class="event-overview"><div class="panel-title"><div><h2>Your upcoming event</h2><p>Manage your ticket collection and sales.</p></div><button class="secondary">Manage event →</button></div><div class="event-summary"><div class="mini-art">${eventArt('neon')}</div><div class="summary-main"><span class="status live">● Live sale</span><h3>Neon Nights: Live in Mumbai</h3><p>24 August · Dome, NSCI · Mumbai</p><div class="bar-label"><span>428 of 500 tickets sold</span><b>85.6%</b></div><div class="progress"><i style="width:85.6%"></i></div></div><div class="summary-stats"><div><span>Face value</span><b>₹1,499</b></div><div><span>Resale cap</span><b>₹1,649</b></div><div><span>Royalty</span><b>5%</b></div></div></div></section><section class="activity"><div class="panel-title"><div><h2>Recent on-chain activity</h2><p>Live updates from your event contract.</p></div><button class="text-button">View all →</button></div>${[['Ticket #0241','Minted to 0x72d…A91C','2 mins ago','Mint'],['Ticket #0188','Resold · ₹1,550 · royalty paid','18 mins ago','Resale'],['Ticket #0310','Minted to 0x4be…29F1','34 mins ago','Mint']].map(x=>`<div class="activity-row"><span class="activity-icon">${x[3] === 'Mint' ? '✦' : '↻'}</span><div><b>${x[0]}</b><p>${x[1]}</p></div><span>${x[2]}</span><em>${x[3]}</em></div>`).join('')}</section></section></main>`; }

function how() { return `<main class="how-page"><section class="how-hero"><span class="eyebrow">THE TECHNOLOGY, SIMPLIFIED</span><h1>Real tickets. <em>Real ownership.</em></h1><p>BlockTix uses Polygon to make event access secure, transparent, and fair for everyone.</p></section><section class="timeline">${[['01','Event is created','The organizer defines ticket supply, price, and resale policy. A smart contract is deployed on Polygon.'],['02','Tickets are minted as NFTs','Each ticket gets a unique token ID. It cannot be duplicated or altered.'],['03','You buy and own it','Payment confirms a blockchain transaction and the NFT is delivered to your wallet.'],['04','Scan, verify, redeem','At the gate, BlockTix checks the current NFT owner and marks the ticket redeemed.']].map(s=>`<article><span>${s[0]}</span><h2>${s[1]}</h2><p>${s[2]}</p></article>`).join('')}</section><section class="protocol"><span class="eyebrow">WHY POLYGON</span><h2>Built for the real world.</h2><div><p>Low transaction fees</p><p>Ethereum-compatible security</p><p>Fast finality at the gate</p><p>Transparent resale history</p></div></section></main>`; }

function modal(content) { return `<div class="modal-backdrop" onclick="closeModal(event)"><div class="modal" onclick="event.stopPropagation()">${content}</div></div>`; }
function render() { let body = state.view === 'home' ? home() : state.view === 'detail' ? detail() : state.view === 'tickets' ? tickets() : state.view === 'dashboard' ? dashboard() : how(); document.getElementById('app').innerHTML = (state.view === 'dashboard' ? '' : header()) + body; if (state.view === 'tickets' && state.booked) [...document.querySelectorAll('.ticket-actions .text-button')].forEach(button => button.onclick = openResale); }
window.go = view => { state.view = view; render(); window.scrollTo(0, 0); };
window.selectEvent = i => { state.selected = i; go('detail'); };
window.setFilter = filter => { state.filter = filter; render(); document.getElementById('events')?.scrollIntoView(); };
window.searchEvents = query => { state.search = query; render(); document.querySelector('.search input')?.focus(); };
window.clearFilters = () => { state.filter = 'All events'; state.search = ''; render(); };
window.openAuth = () => { document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">◉</span><span class="eyebrow">SECURE ACCOUNT ACCESS</span><h2>Sign in to BlockTix</h2><p>Authenticate your account before connecting a wallet or making a blockchain transaction.</p><div class="auth-form"><label>Full name<input id="auth-name" value="${state.user.name}" /></label><label>Email address<input id="auth-email" type="email" value="${state.user.email}" /></label><label>Mobile number<input id="auth-phone" type="tel" value="${state.user.phone}" /></label><label>Password<input type="password" value="blocktix" /></label></div><p class="demo-note">Prototype demo: sample details are pre-filled and no real password is stored.</p><button class="primary full" onclick="completeAuth()">Verify account & connect wallet →</button>`)); };
window.completeAuth = () => { state.user.name = document.getElementById('auth-name').value || state.user.name; state.user.email = document.getElementById('auth-email').value || state.user.email; state.user.phone = document.getElementById('auth-phone').value || state.user.phone; state.authenticated = true; state.wallet = true; render(); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✓</span><span class="eyebrow">ACCOUNT VERIFIED</span><h2>Wallet connected securely.</h2><p>Welcome, ${state.user.name.split(' ')[0]}. Your BlockTix account is authenticated and wallet <b>0x72d…A91C</b> is ready for transactions.</p><button class="primary full" onclick="document.querySelector('.modal-backdrop').remove()">Continue →</button>`)); };
window.openAccount = () => { document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">${state.user.name.split(' ').map(n => n[0]).join('')}</span><span class="eyebrow">YOUR BLOCKTIX ACCOUNT</span><h2>${state.user.name}</h2><div class="account-details"><div><span>Email</span><b>${state.user.email}</b></div><div><span>Mobile</span><b>${state.user.phone}</b></div><div><span>City</span><b>${state.user.city}</b></div><div><span>Wallet status</span><b class="verified-text">● Verified & connected</b></div></div><p class="demo-note">Your personal details identify the customer account; wallet ownership verifies the transaction.</p><button class="secondary full" onclick="document.querySelector('.modal-backdrop').remove()">Close</button>`)); };
window.connectWallet = () => { if (!state.authenticated) return openAuth(); state.wallet = true; render(); };
window.purchase = () => { const e = events[state.selected]; if (!state.wallet) return connectWallet(); if (state.balance < e.price) return document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">!</span><span class="eyebrow">INSUFFICIENT BALANCE</span><h2>Your demo wallet needs funds.</h2><p>This ticket costs ${inr(e.price)}, but your current balance is ${inr(state.balance)}.</p><button class="secondary full" onclick="document.querySelector('.modal-backdrop').remove()">Close</button>`)); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✦</span><span class="eyebrow">TRANSACTION CONFIRMED</span><h2>Your ticket and reward are minted.</h2><p>Ticket <b>#0241</b> and your free <b>Neon Nights Attendance Badge</b> are now owned by your wallet on Polygon Amoy.</p><div class="tx"><span>Transaction hash</span><b>0x7f3a…e491 ↗</b></div><button class="primary full" onclick="finishPurchase()">View my collection →</button>`)); };
window.finishPurchase = () => { state.booked = true; state.balance -= events[state.selected].price; go('tickets'); };
window.openResale = () => { const price = state.resaleListing?.price || 1499; document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">↻</span><span class="eyebrow">AUTHORIZED RESALE</span><h2>List Ticket #0241</h2><p>Set your price. The event organizer limits resale to ${inr(1649)} and automatically receives a 5% royalty.</p><label class="price-field"><span>Listing price (₹)</span><input id="resale-price" type="number" min="1" max="1649" value="${price}" /></label><p class="resale-error" id="resale-error"></p><button class="primary full" onclick="publishResale()">Publish listing →</button></div>`)); };
window.publishResale = () => { const price = Number(document.getElementById('resale-price').value); const error = document.getElementById('resale-error'); if (!price || price < 1) { error.textContent = 'Enter a valid resale price.'; return; } if (price > 1649) { error.textContent = 'This event has a maximum resale price of ₹1,649.'; return; } state.resaleListing = { price }; go('home'); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✓</span><span class="eyebrow">LISTING PUBLISHED</span><h2>Your ticket is live.</h2><p>Ticket #0241 is listed for ${inr(price)}. The Polygon smart contract prevents it from being sold above the organizer’s ₹1,649 cap.</p><button class="primary full" onclick="document.querySelector('.modal-backdrop').remove()">View listing</button>`)); };
window.buyResale = () => { state.resaleListing = null; state.resaleSold = true; document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✓</span><span class="eyebrow">OWNERSHIP TRANSFERRED</span><h2>Resale complete.</h2><p>Ticket #0241 was transferred from wallet <b>0x72d…A91C</b> to buyer wallet <b>0x4be…29F1</b>. The organizer’s 5% royalty was recorded by the Polygon smart contract.</p><div class="tx"><span>Transaction hash</span><b>0x91ca…4d8f ↗</b></div><button class="primary full" onclick="go('home')">Back to events →</button>`)); };
window.redeem = () => { document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon qr-big">▦</span><span class="eyebrow">ENTRY PASS</span><h2>Ready to scan</h2><p>Present this dynamic QR code at the event entrance. The scanner verifies your wallet ownership before marking Ticket #0241 as redeemed.</p><button class="secondary full" onclick="document.querySelector('.modal-backdrop').remove()">Done</button>`)); };
window.closeModal = e => { if (e.target === e.currentTarget) e.currentTarget.remove(); };
window.createEvent = () => document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">+</span><span class="eyebrow">NEW EVENT</span><h2>Event creator</h2><p>This next step would configure the event smart contract: ticket supply, face value, resale limit, and organizer royalty.</p><button class="primary full" onclick="document.querySelector('.modal-backdrop').remove()">Got it</button>`));
// User-facing demo flow. These overrides deliberately keep data in memory: no customer database is used yet.
window.openAuth = () => { document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">◉</span><span class="eyebrow">STEP 1 OF 2 · ACCOUNT VERIFICATION</span><h2>Sign in securely</h2><p>Enter your details and we will send a one-time verification code to your mobile number.</p><div class="auth-form"><label>Full name<input id="auth-name" value="${state.user.name}" /></label><label>Email address<input id="auth-email" type="email" value="${state.user.email}" /></label><label>Mobile number<input id="auth-phone" type="tel" value="${state.user.phone}" /></label></div><p class="demo-note">Demo mode: no details are stored and the verification code is shown on the next screen.</p><button class="primary full" onclick="sendLoginCode()">Send verification code →</button>`)); };
window.sendLoginCode = () => { state.user.name = document.getElementById('auth-name').value || state.user.name; state.user.email = document.getElementById('auth-email').value || state.user.email; state.user.phone = document.getElementById('auth-phone').value || state.user.phone; state.loginCode = String(Math.floor(100000 + Math.random() * 900000)); document.querySelector('.modal-backdrop').remove(); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">#</span><span class="eyebrow">STEP 2 OF 2 · OTP CONFIRMATION</span><h2>Enter your one-time code</h2><p>A six-digit code was sent to ${state.user.phone}. It expires after this verification attempt.</p><div class="otp-code">${state.loginCode}</div><p class="demo-note">In production this code is sent by SMS or email; it is displayed here only for the demo.</p><div class="otp-form"><input id="login-otp" inputmode="numeric" maxlength="6" placeholder="000000" /><button class="primary" onclick="verifyLoginCode()">Verify</button></div>`)); };
window.verifyLoginCode = () => { const supplied = document.getElementById('login-otp').value; if (supplied !== state.loginCode) return document.getElementById('login-otp').focus(); state.loginCode = ''; state.authenticated = true; state.wallet = true; render(); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✓</span><span class="eyebrow">ACCOUNT VERIFIED</span><h2>You are ready to buy tickets.</h2><p>Your demo account and wallet <b>0x72d…A91C</b> are connected for this session.</p><button class="primary full" onclick="document.querySelector('.modal-backdrop').remove()">Continue →</button>`)); };
window.purchase = () => { const e = events[state.selected]; if (!state.wallet) return connectWallet(); if (state.balance < e.price) return document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">!</span><h2>Insufficient demo balance</h2><p>You need ${inr(e.price)} to buy this ticket.</p>`)); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">1</span><span class="eyebrow">CHECKOUT · REVIEW</span><h2>Review your ticket</h2><div class="checkout-summary"><div><span>Event</span><b>${e.name}</b></div><div><span>Ticket</span><b>General Admission × 1</b></div><div><span>Wallet</span><b>0x72d…A91C</b></div><div><span>Total</span><b>${inr(e.price)}</b></div></div><p>Confirm only if these details are correct. The next step simulates the wallet signature and NFT mint.</p><button class="primary full" onclick="confirmPurchase()">Confirm details →</button>`)); };
window.confirmPurchase = () => { const e = events[state.selected]; document.querySelector('.modal-backdrop').remove(); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">2</span><span class="eyebrow">CHECKOUT · WALLET CONFIRMATION</span><h2>Confirm blockchain transaction</h2><p>Your wallet will pay ${inr(e.price)} and mint one ticket NFT. This second confirmation prevents accidental purchases.</p><ul class="security-list"><li><i>✓</i>Exact ticket price is checked</li><li><i>✓</i>Supply limit is checked</li><li><i>✓</i>Ticket is minted once to your wallet</li></ul><button class="primary full" onclick="mintDemoTicket()">Sign & mint ticket →</button>`)); };
window.mintDemoTicket = () => { const e = events[state.selected]; state.booked = true; state.balance -= e.price; e.stock -= 1; state.ticketTokenId = Math.floor(1000 + Math.random() * 8999); document.querySelector('.modal-backdrop').remove(); go('tickets'); };
window.redeem = async () => { if (state.ticketRedeemed) return document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">!</span><span class="eyebrow">ALREADY REDEEMED</span><h2>This ticket has been used.</h2><p>The on-chain redemption flag prevents the same token from being accepted twice.</p>`)); const nonce = crypto.getRandomValues(new Uint32Array(1))[0].toString(16); const payload = `${state.ticketTokenId}:${nonce}:${Date.now() + 60000}`; const bytes = new TextEncoder().encode(payload); const digest = await crypto.subtle.digest('SHA-256', bytes); const hash = [...new Uint8Array(digest)].map(n => n.toString(16).padStart(2, '0')).join(''); state.entryCode = String(Math.floor(100000 + Math.random() * 900000)); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon qr-big">▦</span><span class="eyebrow">DYNAMIC ENTRY PASS</span><h2>Gate verification required</h2><p>Show this rotating code to the gate attendant. It is valid for 60 seconds and is paired with a one-time SHA-256 challenge.</p><div class="otp-code">${state.entryCode}</div><div class="entry-proof"><div><span>Token</span><b>#${state.ticketTokenId}</b></div><div><span>Challenge hash</span><b>${hash.slice(0, 22)}…</b></div><div><span>Contract action</span><b>redeemTicket(tokenId)</b></div></div><p class="demo-note">For the presentation, use “Simulate gate scan.” A real scanner would verify wallet ownership, then call the contract to set the irreversible redeemed flag.</p><button class="primary full" onclick="confirmEntry()">Simulate gate scan →</button>`)); };
window.confirmEntry = () => { state.ticketRedeemed = true; document.querySelector('.modal-backdrop').remove(); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✓</span><span class="eyebrow">ENTRY VERIFIED</span><h2>Ticket redeemed once.</h2><p>The token is now marked as used. A second gate scan is rejected by the smart contract.</p><button class="primary full" onclick="document.querySelector('.modal-backdrop').remove()">Done</button>`)); };
const demoAccounts = [
  { username: 'riya', password: 'BlockTix@2026', name: 'Riya Sharma', email: 'riya.sharma@example.com' },
  { username: 'arjun', password: 'TicketChain@2026', name: 'Arjun Mehta', email: 'arjun.mehta@example.com' },
  { username: 'sana', password: 'EventPass@2026', name: 'Sana Khan', email: 'sana.khan@example.com' }
];
let pendingLogin = null;
const loginPage = () => `<main class="login-page"><section class="login-visual"><button class="brand" onclick="go('home')"><span class="brand-mark">B</span>BlockTix</button><span class="eyebrow">SECURE TICKET MARKETPLACE</span><h1>Your wallet.<br><em>Your access.</em></h1><p>Sign in to browse events, own verifiable NFT tickets, and access your dynamic event pass.</p><div class="login-chain"><i></i><span>Polygon Amoy test network</span></div></section><section class="login-panel"><div class="login-card"><button class="back" onclick="go('home')">← Back to marketplace</button><span class="eyebrow">DEMO ACCOUNT LOGIN</span><h2>Welcome back.</h2><p>Choose one of the sample accounts below, or type its username and password.</p><div class="sample-accounts">${demoAccounts.map(account => `<button onclick="fillSample('${account.username}')"><b>${account.name}</b><span>@${account.username}</span></button>`).join('')}</div><form onsubmit="submitLogin(event)"><label>Username<input id="login-username" autocomplete="username" placeholder="riya" required /></label><label>Password<input id="login-password" type="password" autocomplete="current-password" placeholder="Enter sample password" required /></label><label>Verification email<input id="login-email" type="email" placeholder="name@example.com" required /></label><button class="primary full" type="submit">Continue with email OTP →</button></form><p class="demo-note">Demo credentials are shown for review purposes. No password or email is stored, and no real email is sent.</p></div></section></main>`;
window.openAuth = () => go('login');
window.fillSample = (username) => { const account = demoAccounts.find(item => item.username === username); document.getElementById('login-username').value = account.username; document.getElementById('login-password').value = account.password; document.getElementById('login-email').value = account.email; };
window.submitLogin = (event) => { event.preventDefault(); const username = document.getElementById('login-username').value.trim().toLowerCase(); const password = document.getElementById('login-password').value; const email = document.getElementById('login-email').value.trim(); const account = demoAccounts.find(item => item.username === username && item.password === password); if (!account) return document.querySelector('.login-card').insertAdjacentHTML('beforeend', '<p class="login-error">Use one of the three sample account credentials shown above.</p>'); pendingLogin = { ...account, email }; state.loginCode = String(Math.floor(100000 + Math.random() * 900000)); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✉</span><span class="eyebrow">EMAIL OTP VERIFICATION</span><h2>Verify your email</h2><p>A one-time code was sent to <b>${email}</b>.</p><div class="otp-code">${state.loginCode}</div><p class="demo-note">Prototype mode: this is the code that an email provider would send in production.</p><div class="otp-form"><input id="email-login-otp" inputmode="numeric" maxlength="6" placeholder="000000" /><button class="primary" onclick="verifyEmailLogin()">Verify</button></div>`)); };
window.verifyEmailLogin = () => { if (document.getElementById('email-login-otp').value !== state.loginCode) return document.getElementById('email-login-otp').focus(); state.user.name = pendingLogin.name; state.user.email = pendingLogin.email; state.authenticated = true; state.wallet = true; state.loginCode = ''; pendingLogin = null; document.querySelector('.modal-backdrop').remove(); go('home'); };
window.confirmPurchase = () => { const e = events[state.selected]; state.loginCode = String(Math.floor(100000 + Math.random() * 900000)); document.querySelector('.modal-backdrop').remove(); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">✉</span><span class="eyebrow">PURCHASE SECURITY CHECK</span><h2>Confirm ticket purchase</h2><p>Before the wallet transaction, verify the email registered to your BlockTix account: <b>${state.user.email}</b>.</p><div class="checkout-summary"><div><span>Event</span><b>${e.name}</b></div><div><span>Total</span><b>${inr(e.price)}</b></div></div><div class="otp-code">${state.loginCode}</div><p class="demo-note">Demo mode: this code would be delivered to the registered email address.</p><div class="otp-form"><input id="purchase-otp" inputmode="numeric" maxlength="6" placeholder="000000" /><button class="primary" onclick="verifyPurchaseOtp()">Confirm</button></div>`)); };
window.verifyPurchaseOtp = () => { if (document.getElementById('purchase-otp').value !== state.loginCode) return document.getElementById('purchase-otp').focus(); state.loginCode = ''; document.querySelector('.modal-backdrop').remove(); document.getElementById('app').insertAdjacentHTML('beforeend', modal(`<span class="modal-icon">2</span><span class="eyebrow">CHECKOUT · WALLET CONFIRMATION</span><h2>Confirm blockchain transaction</h2><p>Your wallet will now pay for one ticket NFT. The contract checks price, supply, and mints the token to your wallet.</p><ul class="security-list"><li><i>✓</i>Email purchase confirmation completed</li><li><i>✓</i>Exact ticket price and supply verified</li><li><i>✓</i>One unique ERC-721 ticket minted</li></ul><button class="primary full" onclick="mintDemoTicket()">Sign & mint ticket →</button>`)); };
const baseRender = render;
render = () => { if (state.view === 'login') { document.getElementById('app').innerHTML = loginPage(); return; } baseRender(); if (state.view === 'tickets' && state.booked) { const event = events[state.selected]; const title = document.querySelector('.owned-title h2'); const details = document.querySelector('.owned-title p'); const token = document.querySelector('.nft-data b'); const art = document.querySelector('.owned-art .event-art'); if (title) title.textContent = event.name; if (details) details.textContent = `${event.date}, 2026 · ${event.time} · ${event.venue}`; if (token) token.textContent = `#${state.ticketTokenId}`; if (art) art.className = `event-art ${event.image}`; } };
render();
